
spring:
  application:
    name: eurekaclient1
server:
  port: 2021
eureka:
  instance:
    #服务实例名
    instance-id: ${spring.application.name}:${server.port}
    #访问优先显示IP地址，而不是实例名
    prefer-ip-address: true
    #心跳时间
    lease-renewal-interval-in-seconds: 30
    #发呆时间
    lease-expiration-duration-in-seconds: 90
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

