

spring:
  application:
    name: eurekaserver

server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #自我保护关闭
    eviction-interval-timer-in-ms: 1000  #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
      # 设置是否将自己作为客户端注册到注册中心（缺省true）
      # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false #是否向服务中心注册自己
      # 设置是否从注册中心获取注册信息（缺省true）
      # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
#    fetch-registry: false
      # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
            # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
